### PR TITLE
fixed issue #76 and updated tests

### PR DESCRIPTION
**Pull request by bruno-fs**
this PR should finally fix issue  #76

the updated tests are finally passing on [travis](https://travis-ci.org/varnion/django-dajaxice-ng) 

hopefully these changes will also make this code compatible with older versions of django (at least the tests are working)

### CODE REVIEW

**Comment by bruno-fs** [comment]
I'd like to give 3 suggestions, if I may:
- rename this repo to **django-dajaxice-ng**
- ask [github support](https://github.com/contact) to turn this fork into a standalone repo
- enable [travis-ci](https://travis-ci.org/ifanrx/django-dajaxice) support on the repo

**Comment by bruno-fs** [comment]
if u change this repo into a standalone repo we could try this [tool](https://github.com/IQAndreas/github-issues-import) to import all the issues back here

**Comment by difanz** [comment]
Thanks for the pull request! Our team will be reviewing this PR shortly.

**Comment by bruno-fs** [comment]
did this break anything? lemme know and I can work on a fix :wink:

**Comment by difanz** [comment]
Hi,

Our team is a bit busy recently... Will try to review ASAP.

**Comment by johndeng** [comment]
@varnion Thanks for this PR

**Comment by bruno-fs** [comment]
@johndeng Great! When will this change be pushed to pypi?

**Comment by johndeng** [comment]
@varnion pushed.

FYI https://pypi.python.org/pypi/django-dajaxice-ng

**Pull request merged**
